# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6485ee42ea364aeaff74b0096abb738ff2c9f17a112ba40557089c8ad4b66e8cadea80e6b7ab6f75f8b47277c9434d583eb4c90c06fec14994bc744bab593cb6

test:
  secret_key_base: ddea29ff54953658ce18df1c7c377db5906de55b26bf499b9e754efd819b8c54ae1689fbf8b14f1208e995edc4b950fd0639255f2c52f3ab490398d2a1db8479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
